import JSZip from 'jszip';
import { slugify } from '../utils/slug';
import { templates } from './templates';
import type { Feature, Workspace } from './types';

export interface ExportOptions {
  includeTemplates: boolean;
  includeEmptyFeatures: boolean;
}

export type ExportFormat = 'zip' | 'combined-md';

export const DEFAULT_EXPORT_OPTIONS: ExportOptions = {
  includeTemplates: true,
  includeEmptyFeatures: false,
};

export interface ExportFile {
  path: string;
  content: string;
}

const README_BODY = `# Spec Kit workspace export

This bundle was generated by [Spec Kit Playground](https://nicksanft.github.io/SpecKitPlayground/).

## How to use it

1. Unzip this file at the root of your project (it will create a \`.specify/\` directory).
2. From there, install the official Spec Kit CLI and continue with your agent of choice — see <https://github.com/github/spec-kit>.
3. Or just keep editing in your favourite editor; the markdown is yours.

## Conventions

- One \`tasks.md\` per feature (not a folder of task files). This matches the current Spec Kit template; it is the only convention this bundle relies on.
- Feature directories are numbered \`NNN-slug\` and never recycle numbers, even after deletion.
`;

function endsWithNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}

function isFeatureEmpty(feature: Feature): boolean {
  return (
    feature.spec.content === templates.spec &&
    feature.plan.content === templates.plan &&
    feature.tasks.content === templates.tasks
  );
}

function paddedFeatureNumber(n: number): string {
  return String(n).padStart(3, '0');
}

export function buildExportTree(workspace: Workspace, options: ExportOptions): ExportFile[] {
  const files: ExportFile[] = [];

  files.push({
    path: '.specify/memory/constitution.md',
    content: endsWithNewline(workspace.constitution.content),
  });

  for (const feature of workspace.features) {
    if (!options.includeEmptyFeatures && isFeatureEmpty(feature)) continue;
    const dir = `.specify/specs/${paddedFeatureNumber(feature.number)}-${feature.slug}`;
    files.push({ path: `${dir}/spec.md`, content: endsWithNewline(feature.spec.content) });
    files.push({ path: `${dir}/plan.md`, content: endsWithNewline(feature.plan.content) });
    files.push({ path: `${dir}/tasks.md`, content: endsWithNewline(feature.tasks.content) });
  }

  if (options.includeTemplates) {
    files.push({ path: '.specify/templates/spec-template.md', content: templates.spec });
    files.push({ path: '.specify/templates/plan-template.md', content: templates.plan });
    files.push({ path: '.specify/templates/tasks-template.md', content: templates.tasks });
  }

  files.push({ path: 'README.md', content: README_BODY });

  return files;
}

export interface FileTreeNode {
  name: string;
  isDir: boolean;
  children?: FileTreeNode[];
}

export function buildFileTreeView(files: readonly ExportFile[]): FileTreeNode[] {
  const root: FileTreeNode = { name: '/', isDir: true, children: [] };

  for (const file of files) {
    const segments = file.path.split('/');
    let cursor = root;
    for (let i = 0; i < segments.length; i += 1) {
      const segment = segments[i];
      if (!segment) continue;
      const isLeaf = i === segments.length - 1;
      let node = cursor.children?.find((c) => c.name === segment);
      if (!node) {
        node = { name: segment, isDir: !isLeaf };
        if (!isLeaf) node.children = [];
        cursor.children?.push(node);
      }
      if (!isLeaf) {
        cursor = node;
      }
    }
  }

  sortTree(root);
  return root.children ?? [];
}

function sortTree(node: FileTreeNode): void {
  if (!node.children) return;
  node.children.sort((a, b) => {
    if (a.isDir !== b.isDir) return a.isDir ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  for (const child of node.children) sortTree(child);
}

export async function buildZip(workspace: Workspace, options: ExportOptions): Promise<Blob> {
  const files = buildExportTree(workspace, options);
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  return await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}

export function workspaceFilename(workspace: Workspace, format: ExportFormat = 'zip'): string {
  const slug = slugify(workspace.name);
  const base = slug || 'spec-kit-workspace';
  return format === 'zip' ? `${base}.zip` : `${base}.md`;
}

/* Combined-markdown format
 *
 * One file containing the whole workspace, delimited by HTML-comment
 * markers that don't render in markdown previews but are machine-readable
 * for round-trip. Marker syntax:
 *
 *   <!-- spk:workspace name="..." v="1" -->
 *   <!-- spk:constitution -->
 *   ...constitution body...
 *   <!-- spk:feature number="1" slug="..." title="..." doc="spec" -->
 *   ...spec body...
 *   ...
 */

const COMBINED_VERSION = '1';

function escapeAttr(value: string): string {
  return JSON.stringify(value);
}

export function buildCombinedMarkdown(workspace: Workspace, options: ExportOptions): string {
  const out: string[] = [];
  out.push(
    `<!-- spk:workspace name=${escapeAttr(workspace.name)} v=${escapeAttr(COMBINED_VERSION)} -->`,
  );
  out.push('');
  out.push('<!-- spk:constitution -->');
  out.push('');
  out.push(workspace.constitution.content.trimEnd());

  for (const feature of workspace.features) {
    if (!options.includeEmptyFeatures && isFeatureEmpty(feature)) continue;
    for (const doc of ['spec', 'plan', 'tasks'] as const) {
      out.push('');
      out.push(
        `<!-- spk:feature number=${escapeAttr(String(feature.number))} slug=${escapeAttr(
          feature.slug,
        )} title=${escapeAttr(feature.title)} doc=${escapeAttr(doc)} -->`,
      );
      out.push('');
      out.push(feature[doc].content.trimEnd());
    }
  }

  return out.join('\n') + '\n';
}

export function triggerBlobDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function downloadDocAsMarkdown(filename: string, content: string): void {
  const blob = new Blob([endsWithNewline(content)], { type: 'text/markdown;charset=utf-8' });
  triggerBlobDownload(blob, filename);
}
